#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace NovaGameplayTags
{
	// --- 기본 마우스 조작 ---
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Select); // 좌클릭: 선택 / 드래그
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Command); // 우클릭: 스마트 명령 (이동/공격/상호작용)

	// --- RTS 표준 명령 (단축키) ---
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move); // M: 강제 이동
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Attack); // A: 스마트 공격 / 공격 이동
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Stop); // S: 정지
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Hold); // H: 홀드 (제자리 대기)
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Patrol); // P: 순찰
	
	// --- Shift를 눌렀을 때 명령 ---
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Modifier_Select);

	// --- 노바 1492 고유 명령 ---
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Spread); // C: 산개
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Halt); // L: 완전 정지
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_SelectBase); // B: 기지 선택

	// --- 숫자 키 슬롯 (1~0) ---
	// 부대 지정, 생산, 스킬 등 공용으로 사용되는 슬롯 태그입니다.
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot_1);
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot_2);
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot_3);
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot_4);
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot_5);
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot_6);
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot_7);
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot_8);
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot_9);
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot_0);

	// --- 자원 관련 데이터 태그 ---
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Resource_Watt);
	NOVAREVOLUTION_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Resource_SP);
}
